name: Build, Test and Quality Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-verify:
    name: Build, Test and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Code Formatting
        # Roda o verificador do Prettier diretamente.
        # Ele vai falhar se o código não estiver formatado.
        # (Este passo assume que o Prettier está nas suas devDependencies)
        run: npx prettier --check .

      - name: Lint Code
        # Roda o ESLint diretamente.
        # Ele vai falhar se encontrar erros de lint.
        # (Assume que o ESLint está nas suas devDependencies)
        run: npx eslint . --ext .ts,.tsx

      - name: Check TypeScript Types
        # Este é o passo mais crítico. Continua o mesmo.
        run: npx tsc --noEmit

      - name: Run Security Audit
        # Falhará se encontrar vulnerabilidades de nível ALTO ou CRÍTICO.
        run: npm audit --audit-level=high