name: Build, Test and Quality Check

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-verify:
    name: Build, Test and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        # De volta ao npm install simples.
        # Ele vai ler o package-lock.json (agora com eslint v8) e instalar TUDO.
        run: npm install

      - name: Check Code Formatting
        run: npx prettier --check .

      - name: Lint Code
        # Sem 'env:' A versão v8 instalada localmente será usada
        # e encontrará o .eslintrc.js por padrão.
        run: npx eslint . --ext .ts,.tsx

      - name: Check TypeScript Types
        run: npx tsc --noEmit

      - name: Run Security Audit
        run: npm audit --audit-level=high
